"""add_party_social_tse_to_public_contacts

Revision ID: b4c19e26bcb8
Revises: b3c291f0
Create Date: 2026-05-31 16:44:58.206387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c19e26bcb8'
down_revision: Union[str, Sequence[str], None] = 'b3c291f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_municipalities_ibge_code'), table_name='municipalities')
    op.add_column('public_contacts', sa.Column('party', sa.String(length=100), nullable=True))
    op.add_column('public_contacts', sa.Column('instagram_url', sa.String(length=500), nullable=True))
    op.add_column('public_contacts', sa.Column('facebook_url', sa.String(length=500), nullable=True))
    op.add_column('public_contacts', sa.Column('tse_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_contacts', 'tse_id')
    op.drop_column('public_contacts', 'facebook_url')
    op.drop_column('public_contacts', 'instagram_url')
    op.drop_column('public_contacts', 'party')
    op.create_index(op.f('ix_municipalities_ibge_code'), 'municipalities', ['ibge_code'], unique=False)
    # ### end Alembic commands ###
